# Generated by Django 2.2.1 on 2019-06-04 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autoridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_aut', models.CharField(help_text='Nombre Completo empezando por Nombre, Apellido Paterno, Apellido Materno', max_length=50)),
                ('cargo', models.CharField(help_text='Cargo de la Autoridad', max_length=50)),
                ('adscripcion', models.CharField(help_text='Adscripción de la Autoridad', max_length=100)),
            ],
            options={
                'verbose_name': 'Autoridad',
                'verbose_name_plural': 'Autoridades',
                'ordering': ['nombre_aut'],
            },
        ),
        migrations.CreateModel(
            name='deposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_deposito', models.CharField(help_text='Nombre de Pila del deposito', max_length=50)),
                ('direccion_deposito', models.CharField(help_text='Dirección del deposito', max_length=120)),
                ('fecha_funcion', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('responsable', models.CharField(help_text='Nombre Completo empezando por Nombre, Apellido Paterno, Apellido Materno', max_length=50)),
                ('telefono_resp', models.CharField(help_text='número telefonico', max_length=10)),
            ],
            options={
                'verbose_name': 'Deposito',
                'verbose_name_plural': 'Depositos',
                'ordering': ['nombre_deposito'],
            },
        ),
        migrations.CreateModel(
            name='grua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grua', models.CharField(help_text='Nombre de la Compañia de Gruas', max_length=50)),
                ('grua_tipo', models.CharField(choices=[('O', 'OFICIAL'), ('P', 'PARTICULAR'), ('O', 'OTRO')], default='C', help_text='Elije una opción', max_length=1)),
                ('direccion_grua', models.CharField(help_text='Dirección de la compañia de Gruas', max_length=100)),
                ('telefono_grua', models.CharField(help_text='número telefonico', max_length=10)),
            ],
            options={
                'verbose_name': 'Grua',
                'verbose_name_plural': 'Gruas',
                'ordering': ['nombre_grua'],
            },
        ),
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_oficio', models.CharField(help_text='Ingrese el número de Oficio', max_length=20)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('expediente', models.CharField(choices=[('N', 'NUAT'), ('C', 'CDI'), ('A', 'AP'), ('O', 'OTRO')], default='C', help_text='Elije una opción', max_length=1)),
                ('nombre_aut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocra.Autoridad')),
            ],
            options={
                'verbose_name': 'Oficio',
                'verbose_name_plural': 'Oficios',
                'ordering': ['num_oficio'],
            },
        ),
        migrations.CreateModel(
            name='remite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_remite', models.CharField(help_text='Nombre Completo empezando por Nombre, Apellido Paterno, Apellido Materno', max_length=50)),
                ('cargo_remite', models.CharField(help_text='Cargo de la Autoridad que remite el vehículo', max_length=50)),
                ('adscripcion_remite', models.CharField(help_text='Adscripción de la Autoridad que remite el vehículo', max_length=100)),
                ('telefono', models.CharField(help_text='número telefonico', max_length=10)),
                ('tipo_autoridad', models.CharField(choices=[('PM', 'POLICIA MINISTERIAL'), ('PE', 'POLICIA ESTATAL'), ('PP', 'POLICIA MUNICIPAL'), ('PF', 'POLICIA FEDERAL'), ('O', 'OTRO')], default='PM', help_text='Elije una opción', max_length=1)),
            ],
            options={
                'verbose_name': 'Remitente',
                'verbose_name_plural': 'Remitentes',
                'ordering': ['nombre_remite'],
            },
        ),
        migrations.CreateModel(
            name='vigilante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vigilante', models.CharField(help_text='Nombre Completo empezando por Nombre, Apellido Paterno, Apellido Materno', max_length=50)),
                ('cargo_vigilate', models.CharField(help_text='Cargo del Administrativo', max_length=50)),
                ('expediente', models.CharField(help_text='número telefonico', max_length=10)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vigilante',
                'verbose_name_plural': 'Vigilantes',
                'ordering': ['nombre_vigilante'],
            },
        ),
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_expediente', models.CharField(help_text='Formato = 170/R/2019', max_length=15)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('marca', models.CharField(help_text='Marca del vehículo', max_length=15)),
                ('tipo', models.CharField(help_text='Tipo del vehículo', max_length=15)),
                ('color', models.CharField(help_text='Color del vehículo', max_length=15)),
                ('modelo', models.CharField(help_text='Modelo del vehículo', max_length=4)),
                ('placa', models.CharField(help_text='Número de placa de circulación del vehículo', max_length=10)),
                ('estado', models.CharField(help_text='Estado de las placas de circulación del vehículo', max_length=15)),
                ('serie', models.CharField(help_text='Serie del vehículo', max_length=17)),
                ('motor', models.CharField(help_text='Número del motor del vehículo', max_length=20)),
                ('tipo_auto', models.CharField(choices=[('A', 'AUTOMOVIL / CAMIONETA'), ('B', 'CAMIONETA DE CARGA'), ('C', 'AUTOBUS'), ('D', 'CAMION DE 2 o 3 EJES'), ('E', 'CAMION DE 4 o 5 EJES'), ('F', 'CAMION DE 6,7,8, o 9 EJES'), ('G', 'MOTOCICLETA')], default='A', help_text='Elije una opción', max_length=1)),
                ('estatus', models.CharField(choices=[('P', 'POR PAGAR'), ('G', 'PAGADO'), ('A', 'ABANDONADO'), ('C', 'CHATARRIZACION')], default='P', help_text='Elije una opción', max_length=1)),
                ('fleje', models.CharField(choices=[('S', 'SI'), ('N', 'NO')], default='N', help_text='Elije una opción', max_length=1)),
                ('folio_fleje', models.CharField(help_text='Folio del fleje', max_length=10)),
                ('motivo', models.CharField(choices=[('R', 'ROBADO RECUPERADO'), ('A', 'ASEGURADO'), ('C', 'CATEO'), ('O', 'OTRO')], default='R', help_text='Elije una opción', max_length=1)),
                ('procedencia', models.CharField(choices=[('P', 'PARTICULAR'), ('E', 'EMPRESARIAL'), ('O', 'OFICIAL')], default='P', help_text='Elije una opción', max_length=1)),
                ('estado_veh', models.CharField(choices=[('B', 'BUENO'), ('R', 'REGULAR'), ('M', 'MALO')], default='B', help_text='Elije una opción', max_length=1)),
                ('llaves', models.CharField(choices=[('S', 'SI'), ('N', 'NO')], default='N', help_text='Elije una opción', max_length=1)),
                ('funciona', models.CharField(choices=[('S', 'SI'), ('N', 'NO')], default='N', help_text='Elije una opción', max_length=1)),
                ('sellos', models.CharField(choices=[('S', 'SI'), ('N', 'NO')], default='N', help_text='Elije una opción', max_length=1)),
                ('valores', models.CharField(choices=[('S', 'SI'), ('N', 'NO')], default='N', help_text='Elije una opción', max_length=1)),
                ('especifique', models.TextField(blank=True, help_text='Aqui puede hacer descripción de los valores del autos', max_length=200, null=True)),
                ('observacion', models.TextField(blank=True, help_text='Aqui puede hacer observaciones del vehiculo, entre otras', max_length=200, null=True)),
                ('Sasca', models.CharField(blank=True, help_text='Ingrese el número de Sasca', max_length=10, null=True)),
                ('nombre_aut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocra.Autoridad')),
                ('nombre_deposito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocra.deposito')),
                ('nombre_grua', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocra.grua')),
                ('num_oficio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocra.Oficio')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
                'ordering': ['Num_expediente'],
            },
        ),
        migrations.AddField(
            model_name='oficio',
            name='nombre_remite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocra.remite'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='nombre_vigilante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocra.vigilante'),
        ),
        migrations.CreateModel(
            name='devolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_oficio', models.CharField(help_text='Ingrese el número de Oficio', max_length=20)),
                ('fecha_oficio', models.DateField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('hora_entrega', models.TimeField(blank=True, null=True)),
                ('nombre_propietario', models.CharField(help_text='Nombre Completo empezando por Nombre, Apellido Paterno, Apellido Materno', max_length=50)),
                ('identificacion', models.CharField(choices=[('I', 'INE - IFE'), ('C', 'CEDULA PROFESIONAL'), ('P', 'PASAPORTE'), ('L', 'LICENCIA DE CONDUCIR'), ('CM', 'CARTILLA DEL SERVICIO MILITAR'), ('O', 'OTRO')], default='N', help_text='Elije una opción', max_length=1)),
                ('numero_iden', models.CharField(help_text='Número de la identificación', max_length=20)),
                ('telefono_usuario', models.CharField(help_text='Número telefonico', max_length=10)),
                ('correo', models.CharField(help_text='Correo Electronico', max_length=20)),
                ('dias', models.CharField(help_text='Dias a resguardo', max_length=5)),
                ('cobro', models.FloatField(default=0.0)),
                ('descuento', models.CharField(choices=[('A', '0 %'), ('B', '50 %'), ('C', '100 %')], default='A', help_text='Elije una opción', max_length=1)),
                ('cobro_grua', models.FloatField(default=0.0)),
                ('Num_expediente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocra.vehiculo')),
                ('nombre_aut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocra.Autoridad')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['Num_expediente'],
            },
        ),
    ]
