# Generated by Django 2.2.1 on 2019-06-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
