# Generated by Django 2.2.1 on 2019-06-04 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ocra', '0002_auto_20190604_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='numero_exp',
            field=models.CharField(default=django.utils.timezone.now, help_text='Ingrese el número de expediente', max_length=50),
            preserve_default=False,
        ),
    ]
