# Generated by Django 2.2.1 on 2019-06-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocra', '0003_oficio_numero_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remite',
            name='tipo_autoridad',
            field=models.CharField(choices=[('PM', 'POLICIA MINISTERIAL'), ('PE', 'POLICIA ESTATAL'), ('PP', 'POLICIA MUNICIPAL'), ('PF', 'POLICIA FEDERAL'), ('O', 'OTRO')], default='PM', help_text='Elije una opción', max_length=2),
        ),
    ]
