# Generated by Django 2.2.1 on 2019-06-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocra', '0005_auto_20190617_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='identificacion',
            field=models.CharField(choices=[('I', 'INE - IFE'), ('C', 'CEDULA PROFESIONAL'), ('P', 'PASAPORTE'), ('L', 'LICENCIA DE CONDUCIR'), ('CM', 'CARTILLA DEL SERVICIO MILITAR'), ('O', 'OTRO')], default='N', help_text='Elije una opción', max_length=2),
        ),
        migrations.AlterField(
            model_name='grua',
            name='grua_tipo',
            field=models.CharField(choices=[('O', 'OFICIAL'), ('P', 'PARTICULAR'), ('T', 'OTRO')], default='C', help_text='Elije una opción', max_length=1),
        ),
    ]
